# Generated by Django 5.0.1 on 2024-02-09 23:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('tipo_item', models.CharField(choices=[('APARTAMENTO, APARTAMENTO', 'Apartemento'), ('KITNET, KITNET', 'Kitnet'), ('CASA, CASA', 'Casa')], max_length=100)),
                ('endereco', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esta_locado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Imovel',
                'verbose_name_plural': 'Imoveis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImovelImagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images', verbose_name='imagens')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_imovel', to='base.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_start', models.DateTimeField(verbose_name='Inicio')),
                ('dt_end', models.DateTimeField(verbose_name='Final')),
                ('criado_em', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_locacao', to='base.imovel')),
            ],
            options={
                'verbose_name': 'Registrar Locação',
                'verbose_name_plural': 'Registrar Locação',
                'ordering': ['-id'],
            },
        ),
    ]
